*ESERCIZIO IN CUI RX E TX SONO ENTRAMBI CON INTERRUPT
*RX (scritto da solo) TOP, MOLTO BENE

*-----AREA DATI-----OK

	ORG	$8000
MSG	DS.B	6
DIM	DC.B	6
COUNT	DC.B	0

*------AREA MAIN----

	ORG	$8200
PIADA	EQU	$2004
PIACA	EQU $2005

MAIN	JMP	INIZIALIZZAPIA

	MOVE.W	SR,D0
	ANDI.W	#$D8FF,D0 *MASCHERA REG STATO, INT ABILITATI
	MOVE.W	D0,SR

LOOP	JMP	LOOP


*---------------------- ROUNTINE DI INIZIALIZZAZIONE PIA --------- OK

INIZIALIZZAPIA	MOVE.L	#0,PIACA
	MOVE.L	#$00,PIADA
	MOVE.L	#$00100101,PIACA
	RTS
	
*---------------------- ISR --------------- OK

		ORG	$8700
		*SALVATAGGIO DEL CONTESTO
INT3	MOVE.L	A1,-(A7)
		MOVE.L	A0,-(A7)
		MOVE.L	D0,-(A7)
		
		MOVEA.L	#PIADA,A1
		MOVEA.L	#MSG,A0
		MOVE.B	COUNT,D0

		MOVE.B(A1),(A0,D0)
		ADD.B	#1,D0
		MOVE.B	D0,COUNT
		
		*RIPRISTINO DEL CONTESTO
		MOVE.L	(A7)+,D0
		MOVE.L	(A7)+,A0
		MOVE.L	(A7)+,A1
		
END MAIN