*ESERCIZIO IN CUI RX E TX SONO ENTRAMBI CON INTERRUPT
*TX (scritto da solo) TOP, MOLTO BENE

*--------- AREA DATI ------- OK

	ORG	$8000
MSG	DC.B	1,2,3,4,5,6
DIM	DC.B	6
COUNT	DC.B	0

*--------- AREA MAIN -------- 
	ORG	$8200
PIADB	EQU	$2006
PIACB	EQU	$2007

MAIN	JMP	INIZIALIZZAPIA

	MOVEA.L	#PIACB,A1
	MOVEA.L	#PIADB,A2
	MOVEA.L	#MSG,A0

	MOVE.W	SR,D0
	ANDI.W	#$D8FF,D0
	MOVE.W	D0,SR *FINO A QUA OK, FATTIBILE

INVIOPRIMOCHAR	MOVE.B	(A2),D1 *FITTIZIA
	MOVE.B	(A0),(A2)
	MOVE.B	#1,COUNT

LOOP JMP LOOP



*------- ROUTINE DI INIZIALIZZAZIONE PIAB ------ OK

INIZIALIZZAPIA	MOVE.L	#0,PIACB
	MOVE.L	#$FF,PIADB
	MOVE.L	#$00100100,PIACB
	RTS
	

*------- ISR -------------- OK MA SNI, MIGLIORABILE LA PARTE INVIO
	ORG	$8800
INT4	MOVE.L	A1,-(A7)
		MOVE.L	A0,-(A7)
		MOVE.L	D0,-(A7)
		MOVE.L	D1,-(A7)
		MOVE.L	D2,-(A7)
		
		
		MOVEA.L	#PIADB,A1
		MOVEA.L	#MSG,A0
		MOVE.B	DIM,D0
		MOVE.B	COUNT,D1
		
		CMP	D0,D1
		BEQ	FINE
		
INVIO	MOVE.B	(A1),D2
		MOVE.B	(A0,D1),(A1)
		ADD.B	#1,D1
		MOVE.B	D1,COUNT
		
		
		
FINE	MOVE.L (A7)+,D2
		MOVE.L (A7)+,D1
		MOVE.L (A7)+,D0
		MOVE.L (A7)+,A0
		MOVE.L (A7)+,A1
	RTE